server:
  port: 8110
spring:
  application:
    name: iw-data
  profiles:
    active: dev
mybatis-plus:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: top.xmlsj.iwdata.entity
  configuration:
    #    开启 sql 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #    配置逻辑删除
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)